server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
  grpc:
    addr: 0.0.0.0:8010
    timeout: 60s
data:
  database:
    driver: postgres
#    source: host=localhost user=postgres password=postgres dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai
    source: "${DATA_DATABASE_SOURCE}"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
file:
  storage_type: rustfs
  rustfs:
    endpoint: https://file.hukss.cn
    access_key: "${RS_ACCESS_KEY}"
    secret_key: "${RS_SECRET_KEY}"
    bucket: blog-files
    region: default
  minio:
    endpoint: 127.0.0.1:9000
    access_key: minioadmin
    secret_key: minioadmin
    bucket: blog-files
    use_ssl: false
  local:
    upload_dir: ./uploads
